language:
    - c

before_install:
    - pip install --user cpp-coveralls

script:
    - qmake 
    - make
    - ./tests/tests

after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    #- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    #- sonar-scanner

cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
    email: false
    
addons:
  sonarcloud:
    organization: "khuaigul"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output <your clean build command>
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
